### ISSUE TITLE
User should have a consistent cancel button experience

### ISSUE THREAD

**Issue by ailisp** [NEAR-DevHub/neardevhub-portal#507]
Acceptance criteria:
- Identify all cancel button existing now and think of places where should have a cancel button but currently not
- For each comment in one sentence where it is and what is the current behavior
- Ping and wait for a UX/Design of the desired/consistent cancel behavior
- Implement that behavior on all buttons

**Comment by itexpert120** [comment]
Currently, all cancel buttons:
- Community Spawner 
![image](https://github.com/near/neardevhub-widgets/assets/46527178/4a5bf277-e59b-4c43-9235-c6e1cfa3e2a5)
- Post Replies
![image](https://github.com/near/neardevhub-widgets/assets/46527178/d24eac21-7d84-4420-94c7-43fac544ed7c)
- Community Configuration Section
![image](https://github.com/near/neardevhub-widgets/assets/46527178/8c5cad1f-e4a5-494b-99a0-a839222900aa)
This one has cancel button twice
