### ISSUE TITLE
Install custom fonts

### ISSUE THREAD

**Issue by sashapais** [NEAR-DevHub/neardevhub-portal#509]
**The objective is to make fonts on the platform consistent with the new brand.**
Would be great to have the ability to add custom fonts, so that we continue to build DevHub's identity through typography too.

**Font Assets**
- Sasha can provide to whoever is working on this ticket

**Comment by ailisp** [comment]
Need some research to confirm we can add custom font and if so, a proper way to integrate it into the build process.

**Comment by itexpert120** [comment]
`const Container = styled.div`
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 100vh;
  background: #f4f4f4;
  margin-top: calc(-1 * var(--body-top-padding));

  @font-face {
    font-family: "Mona Sans";
    src: url("https://raw.githubusercontent.com/itexpert120/fonts/main/Mona-Sans.woff2")
        format("woff2 supports variations"),
      url("https://raw.githubusercontent.com/itexpert120/fonts/main/Mona-Sans.woff2")
        format("woff2-variations");
    font-weight: 200 900;
    font-stretch: 75% 125%;
  }

  font-family: "Mona Sans" !important;
`;`

This way we can use custom fonts on devhub

**Comment by itexpert120** [comment]
@ori-near Can you share with me the font so I can work on this?
