### ISSUE TITLE
Issues with search and filtering of feed

### ISSUE THREAD

**Issue by Megha-Dev-19** [NEAR-DevHub/neardevhub-portal#781]
1) Go to [feed page](https://near.org/devhub.near/widget/app?page=proposals)
2) Filtering and search works sometimes, otherwise it keeps the data same

Check for all instances
- [x] Devhub proposals
- [x] Infrastructure committee -> Rfps and proposals
- [x] Events committee

**Comment by ori-near** [comment]
Problem: I tried clicking the author filter on the proposal feed page. But it's not filtering posts by the author consistently. If I try to click the author a second time, then it works sometimes (see first screenshot). Same issue with stage. I try to filter just by Payment Processing but I see posts with various statuses.

Desired State: When I select an author the first time, I should see only posts by that author (see second screenshot). When I select a specific stage, I should only see posts in that selected stage.


![Image](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/c9662879-ce2a-47c6-8ea0-89ba3685d682)



![Image](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/6738f8a5-fef7-4eb9-8f18-9ef415d7d0b9)

**Comment by Tguntenaar** [comment]
Closing this issue. We are replacing the query API indexer with a cached API from issue [948](https://github.com/NEAR-DevHub/neardevhub-portal/issues/948). The filters / search will have to be reimplemented using this API.
